controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    voltageRatios_broadcaster:
      type: "force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster"

voltageRatios_broadcaster:
  ros__parameters:
    interface_names.force.x: voltageRatios_sensor/voltageRatio01
    interface_names.force.y: voltageRatios_sensor/voltageRatio01
    interface_names.force.z: voltageRatios_sensor/voltageRatio02
    interface_names.torque.x: voltageRatios_sensor/voltageRatio03
    frame_id: tool_link


